### PR TITLE
Form Hack

### PR DESCRIPTION
**Pull request by rawkakani**
To be able to make the submission live, the php will have to be served life, when you ready to push the porfolio to production let me know

### CODE REVIEW

**Comment by Thegrandkardii** [comment]
I have pushed it, must i merge the files?

**Comment by Thegrandkardii** [comment]
also to make the portfolio live i have to host it on hostinger?

**Comment by rawkakani** [comment]
> I have pushed it, must i merge the files?

yes you can merge into main

**Comment by rawkakani** [comment]
> also to make the portfolio live i have to host it on hostinger?

yes but if you use that, you should chat with Andrew so he can help with the PHP, especially if you want to do it this week

**Comment by Thegrandkardii** [comment]
okay noted
Thank you

**Pull request merged**
